// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CancelJob(arg1:string):Promise<boolean>;

export function EnqueuePro(arg1:string,arg2:string,arg3:service.ProConvertOptions):Promise<service.Job>;

export function EnqueueSimple(arg1:Array<string>,arg2:service.SimpleConvertOptions):Promise<Array<service.Job>>;

export function GetConfig():Promise<service.Config>;

export function Jobs():Promise<Array<service.Job>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PickFiles():Promise<Array<string>>;

export function ProbeFiles(arg1:Array<string>):Promise<Array<service.MediaInfo>>;

export function SetMode(arg1:service.Mode):Promise<void>;
