// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function EnqueuePro(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnqueuePro'](arg1, arg2, arg3);
}

export function EnqueueSimple(arg1, arg2) {
  return window['go']['main']['App']['EnqueueSimple'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Jobs() {
  return window['go']['main']['App']['Jobs']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function ProbeFiles(arg1) {
  return window['go']['main']['App']['ProbeFiles'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}
